# Generated by Django 4.1.7 on 2023-06-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_is_admin_higher_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_verified',
        ),
    ]
