# Generated by Django 4.1.7 on 2023-06-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_useraccount_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_admin_higher_level',
            new_name='is_supervisor',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin_lower_level',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin_middle_level',
        ),
    ]
