# Generated by Django 4.1.7 on 2023-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydean',
            name='ranks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
