# Generated by Django 4.1.7 on 2023-03-13 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_req', to=settings.AUTH_USER_MODEL)),
                ('sender_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_req', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptanceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='acceptance_letter')),
                ('text', models.TextField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('receiver_acept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_acept', to=settings.AUTH_USER_MODEL)),
                ('sender_acept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_acept', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
