# Generated by Django 4.1.7 on 2023-06-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthod',
            name='universities',
        ),
    ]
