# Generated by Django 4.1.7 on 2023-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_departmenthod_universities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
