# Generated by Django 4.1.7 on 2023-06-27 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0003_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, max_length=100, null=True)),
                ('id_no', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=100, region=None)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_leave', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('dept_training_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_training_coordinator', to='department.departmenttrainingcoordinator')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_supervisor', to=settings.AUTH_USER_MODEL)),
                ('training_students', models.ManyToManyField(blank=True, related_name='supervisor_training_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
